[package]
name = "grufinity"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", default-features = false }
rand = "0.8.5"
indicatif = "0.17.7"
bincode = "=1.3.3"  # Pin bincode version for compatibility with burn

[features]
default = ["wgpu"]  # Default backend uses WGPU

# Use the features that were successfully added
wgpu = ["burn/wgpu"]
fusion = ["burn/fusion"]
candle = ["burn/candle"]
candle-cuda = ["burn/candle-cuda"]
autodiff = ["burn/autodiff"]
autotune = ["burn/autotune"]

# Combined feature flags for convenience
wgpu-fusion = ["wgpu", "fusion", "autodiff", "autotune"]
candle-fusion = ["candle", "fusion", "autodiff"]
candle-cuda-fusion = ["candle", "candle-cuda", "fusion", "autodiff"]

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[[bin]]
name = "simple_generate"
path = "src/bin/simple_generate.rs"

[[bin]]
name = "tbptt_train"
path = "src/bin/tbptt_train.rs"

