[package]
name = "grufinity"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", default-features = false, features = ["autodiff", "autotune", "candle", "fusion", "ndarray", "tch", "train", "wgpu", "metrics", "cuda-jit", "candle-cuda"] }
rand = "0.8.5"
indicatif = "0.17.7"
bincode = "=2.0.0-rc.3"
bincode_derive = "=2.0.0-rc.3"

[features]
default = ["wgpu"]  # Default backend uses WGPU

# Use the features that were successfully added
wgpu = ["burn/wgpu"]
fusion = ["burn/fusion"]
candle = ["burn/candle"]
tch = ["burn/tch"]
ndarray = ["burn/ndarray"]
autodiff = ["burn/autodiff"]
autotune = ["burn/autotune"]

# Combined feature flags for convenience
wgpu-fusion = ["wgpu", "fusion", "autodiff", "autotune"]
candle-fusion = ["candle", "fusion", "autodiff"]
candle-cuda = ["candle", "burn/candle-cuda", "fusion", "autodiff"]  # CUDA via candle
# add 

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[[bin]]
name = "simple_generate"
path = "src/bin/simple_generate.rs"

[[bin]]
name = "tbptt_train"
path = "src/bin/tbptt_train.rs"

